### PR TITLE
updated protobufs

### PR DESCRIPTION
**Pull request by lauriys**
not sure where you get the .desc files from and stuff but this at least revives the roundstats in the match list

### CODE REVIEW

**Comment by joshuaferrara** [comment]
Really? I've been using the protobufs from the SteamKit repo. Will check this out in a few hours, then potentially merge.

**Comment by joshuaferrara** [comment]
Really? I've been using the protobufs from the SteamKit repo. Will check this out in a few hours, then potentially merge.

**Comment by lauriys** [comment]
SteamKit's protos are outdated though...
https://github.com/SteamDatabase/GameTracking/tree/master/Protobufs/csgo

**Comment by lauriys** [comment]
without those, you can't get the demo link for replays or any of round stats

**Comment by joshuaferrara** [comment]
Thanks for filling me in with a location of newer ProtoBufs - had no clue they were outdated. Merging now.

**Comment by lauriys** [comment]
you should actually be able to reference that repo from this one... i have no idea how this works in git but a feature like that exists ^-^

**Comment by joshuaferrara** [comment]
Yeah I had actually thought about doing that a while back, just haven't looked into it yet. Seems like a super handy feature though as everything will stay updated.

**Comment by lauriys** [comment]
i wish i knew how to git

**Pull request merged**
