### PR TITLE
chore: update csstats link

### PR DESCRIPTION
**Pull request by rchh**
csgostats.gg has moved to csstats.gg! And we're still using the library! 💯

### CODE REVIEW

**Comment by joshuaferrara** [comment]
very cool - done! i haven't been following CS (tech-wise) at all lately. does CS2 still use the same protobufs/game coordinator?

**Comment by rchh** [comment]
Yeah all of the GC stuff is exactly the same fortunately! makes sense tho, no need to rewrite all of those APIs. If they di, well... would need to wait for the gods that did the SteamKit stuff to go again! :D 

you doing good? Been a long time :)

**Review by hossen71 — APPROVED** [review]
e5ef24438506b74b6e3d598663a76ea4c2b78e21

**Review by hossen71 — COMMENTED** [review]
48bc7988febf9e5688883a0822a036567882fee1

**Pull request merged**
