### PR TITLE
Steam 1.1.0 compatibility

### PR DESCRIPTION
**Pull request by TrueCarry**

### CODE REVIEW

**Comment by TrueCarry** [comment]
Added methods to request live games. Disabled camel case like they did in node-steam.

**Comment by joshuaferrara** [comment]
I ran into an issue running the example, could you verify if this is just on my end? Looks like it might be an issue with node-steam.

Test process:
- Cloned https://github.com/TrueCarry/node-csgo.git
- Ran npm-install
- Ran example
- Received error below

nodecsgoissue

**Edit:** Also thank you for taking the time to update the code for the newest version of node-steam, I really appreciate it! :smile:

**Comment by TrueCarry** [comment]
Seems like steam problem, if it installed in different directory everything working fine.

**Comment by TrueCarry** [comment]
If you go to node_modules/steam/ and run npm install protobufjs it apparently works. Do you have any ideas why? 

EDIT: If you make package.json with dependicies like this

``` json
"dependencies": {
    "steam": "*",
    "csgo": "https://github.com/TrueCarry/node-csgo.git"
  }
```

Everything works again. Very strange situation. Waiting for response from node-steam...

**Comment by TrueCarry** [comment]
Seems like it was protobuf error https://github.com/dcodeIO/ProtoBuf.js/issues/310. Fixed by changing dependencies to

``` json
"dependencies": {
    "steam": "1.1.0",
    "protobufjs": "*",
    "deferred": "*",
    "bignumber.js": "^2.0.7",
    "bytebuffer": ">=3.5.5"
  }
```

**Comment by joshuaferrara** [comment]
LGTM! This also fixes issue #9

**Pull request merged**
